# Generated by Django 5.1 on 2024-08-29 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_rename_services_master_master_services_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='master_services',
        ),
    ]
