# Generated by Django 4.2.16 on 2024-09-14 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='clinet',
            new_name='client',
        ),
    ]
